first steps script on scrapeme.live
tinyfish-io/fish-tank pull request #27
Opened 2024-08-05 21:55 UTC by shuhaodo

Script for the "first steps" tutorial using the latest SDK API

https://agentql-docs.vercel.app/getting-started/first-steps

2024-08-06 09:10 UTC, rachelnabors approved these changes

2024-08-06 09:10 UTC, rachelnabors commented
@shuhaodo Should we link to this repo on the site as well, for folks who want to "fork and play?"

2024-08-06 22:07 UTC, colriot requested changes
Added comments for discussion

2024-08-07 17:56 UTC, shuhaodo commented on examples/first_steps/first_steps.py
> +    # API Doc: TODO add API Doc link
good point, removed

2024-08-07 17:58 UTC, shuhaodo commented on examples/first_steps/first_steps.py
> +        browser = playwright.chromium.launch(headless=False)
yes!

2024-08-07 18:00 UTC, shuhaodo commented on examples/first_steps/first_steps.py
> +        page: Page = browser.new_page()
No linter error for me. What's the error on your side?
<img width="546" alt="image" src="https://github.com/user-attachments/assets/45c9cb89-af75-423d-914e-6fa06f72c06d">

2024-08-14 21:01 UTC, frankfeng98 commented
@rachelnabors @shuhaodo I took the liberty of updating this PR since it will be downloaded with `agentql init` command. The main changes are:

(1) All the queries and natural language prompt are created as constant variables, like other examples.
(2) `query_elements()` API is added into the example. So now, first steps examples have all three APIs (elements query, data query, Smart Locator)

Let me know your thoughts! Once this is done, I will also create an async version of the first step script to showcase our asynchronous library.

2024-08-16 01:08 UTC, rachelnabors submitted a review, later dismissed
Looks good! Wanted to expand on each of these three selector options. I think it's worth clarifying them further in the docs

2024-08-16 01:08 UTC, rachelnabors commented on examples/first_steps/first_steps.py
> +    # Find DOM element using AgentQL Elements Query API
```suggestion
    # Find DOM element using AgentQL Elements Query API query_elements()
    # query_elements() returns matching HTML elements
```

2024-08-16 01:08 UTC, rachelnabors commented on examples/first_steps/first_steps.py
> +    # Extract data using AgentQL Data Query API
```suggestion
    # Extract data using AgentQL Data Query API query_data()
    # query_date() returns data from matching elements, not the elements themselves
```

2024-08-16 17:52 UTC, frankfeng98 approved these changes

2024-08-16 17:53 UTC, merged