TF-1404 Add CDP example to fish-tank
tinyfish-io/fish-tank pull request #48
Opened 2024-08-15 22:15 UTC by frankfeng98

This PR fixes TF-1404. 

In this PR, an example is added to showcase how to use CDP (Chrome DevTools Protocol) to connect to local browsers on user machine. The example is consist of two parts:

(1) The method `fetch_data_from_open_website_page()` shows how to fetch data from an existing page in the local browser. This will require users to actually navigate to the page within browser before running the script.
(2) The method `interact_with_new_page_in_local_browser()` shows how to open a new tab in local browser and interact / fetch data from that tab. 

The README includes detailed instructions on how to make CDP work.

2024-08-15 23:53 UTC, rachelnabors approved these changes
Golden!

2024-08-16 04:32 UTC, colriot requested changes
This will make a great example for the docs as well!
Sorry to unapprove, have some comments to address :)

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/README.md
> +- Save this python file locally as **run_script_with_local_browser.py**
```suggestion
- Save this Python file locally as **run_script_with_local_browser.py**.
```

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/README.md
> +- Close your Google Chrome browser application if it is open.
nit: browser or app, don't need both

```suggestion
- Close your Google Chrome application if it is open.
```

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/README.md
> +**Make sure to replace chrome.exe with the path to your Chrome executable if it's not already in your system's PATH.**
```suggestion
**Make sure to replace `chrome.exe` with the path to your Chrome executable if it's not already in your system's PATH.**
```

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/run_script_with_local_browser.py
> +        # Use query_elements() method to locate the search box and search button from the page
fix the comment, pls

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/run_script_with_local_browser.py
> +        browser.close()
I don't think we should do this, since we were not ones who opened it.

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/run_script_with_local_browser.py
> +QUERY_FOR_SCRAPE_ME_1 = """
I suggest to use get_by_prompt if we want to get 1 element (maybe for the first one), and/or add another element to the query (the second query) to use it as query_elements

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/run_script_with_local_browser.py
> +QUERY_FOR_SCRAPE_ME_1 = """
```suggestion
SEARCH_QUERY = """
```

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/run_script_with_local_browser.py
> +QUERY_FOR_SCRAPE_ME_2 = """
```suggestion
STOCK_QUERY = """
```

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/run_script_with_local_browser.py
> +QUERY = """
If we expect a specific page to run this query, let's add instructions to open this page in README

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/README.md
> +This example demonstrates how to run the script in an existing local browser with AgentQL.
Not necessary local, can be remote. Main thing is that it's not bundled.
Please, fix this in other places too.

```suggestion
This example demonstrates how to interact with an external or existing browser with AgentQL.
```

2024-08-16 04:32 UTC, colriot commented on examples/run_script_with_local_browser/README.md
> +- In the open browser, select the Google profile you would like to use for this session.
Not sure what did you mean, but suggestions might be: "open browser dialog" or "In opened browser"?

2024-08-19 03:10 UTC, colriot approved these changes
Lgtm, thanks for addressing comments!

2024-08-19 16:59 UTC, merged